apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name }}
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}
            - name: MONGO_DBNAME
              valueFrom:
                secretKeyRef:
                  key: dbName
                  name: {{ .Release.Name }}
          volumeMounts:
            - name: unifi-db
              mountPath: /data/db
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: unifi-db
          persistentVolumeClaim:
            claimName: unifi-mongo
        - name: init
          configMap:
            name: {{ .Release.Name }}-mongo
