apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  {{- with .Values.mongo.persistence }}
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | quote }}
  accessModes:
    {{- range .accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- with .selectorLabels }}
  selector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
