apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mongo
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo
          volumeMounts:
            - name: unifi-db
              mountPath: /data/db
      volumes:
        - name: unifi-db
          persistentVolumeClaim:
            claimName: unifi-mongo
