apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  user: {{ .Values.mongo.user | b64enc | quote }}
  {{- if .Values.mongo.password }}
  password: {{ .Values.mongo.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  dbName: {{ .Values.mongo.dbName | b64enc | quote }}
