apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-unifi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-unifi
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8443
              hostPort: 8443
            - containerPort: 8880
              hostPort: 8880
            - containerPort: 8843
              hostPort: 8843
            - containerPort: 3478
              hostPort: 3478
              protocol: UDP
            - containerPort: 5514
              hostPort: 5514
              protocol: UDP
            - containerPort: 10001
              hostPort: 10001
              protocol: UDP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name }}
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name }}
            - name: MONGO_DBNAME
              valueFrom:
                secretKeyRef:
                  key: dbName
                  name: {{ .Release.Name }}
          volumeMounts:
            - name: unifi-data
              mountPath: /var/lib/unifi
            - name: unifi-logs
              mountPath: /var/log/unifi
      volumes:
        - name: unifi-data
          persistentVolumeClaim:
            claimName: unifi-unifi
        - name: unifi-logs
          emptyDir: {}
