apiVersion: v2
name: unifi
description: A Helm chart for Unifi Network Controller
type: application
# renovate: depName=unifi
version: "10.4.57-34628-1"
# renovate: depName=unifi
appVersion: "10.4.57-34628-1"
