apiVersion: v2
name: unifi
description: A Helm chart for Unifi Network Controller
type: application
# renovate: depName=unifi
version: "10.3.58-34147-1"
# renovate: depName=unifi
appVersion: "10.3.58-34147-1"
