apiVersion: v2
name: unifi
description: A Helm chart for Unifi Network Controller
type: application
# renovate: depName=unifi
version: "10.2.105-33556-1"
# renovate: depName=unifi
appVersion: "10.2.105-33556-1"
