replicaCount: 1
image:
  repository: ghcr.io/kahowell/unifi
  tag: b778565c44b93ca7fdda53ca685092b77644ccae
  pullPolicy: IfNotPresent

mongo:
  image:
    repository: docker.io/library/mongo
    tag: 8
  user: "ubnt"
  password: ""
  persistence:
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # storageClassName: default
    # selectorLabels: {}

ingress:
  enabled: true
  hostname: unifi.example.com

persistence:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # storageClassName: default
  # selectorLabels: {}
